In [2]:
!pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.24.0-py3-none-any.whl.metadata (7.3 kB)
Collecting scipy>=1.16.3 (from mlxtend)
  Downloading scipy-1.17.0-cp313-cp313-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting numpy>=2.3.5 (from mlxtend)
  Downloading numpy-2.4.2-cp313-cp313-macosx_14_0_arm64.whl.metadata (6.6 kB)
Collecting pandas>=2.3.3 (from mlxtend)
  Downloading pandas-3.0.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting scikit-learn>=1.8.0 (from mlxtend)
  Using cached scikit_learn-1.8.0-cp313-cp313-macosx_12_0_arm64.whl.metadata (11 kB)
Collecting matplotlib>=3.10.8 (from mlxtend)
  Downloading matplotlib-3.10.8-cp313-cp313-macosx_11_0_arm64.whl.metadata (52 kB)
Collecting joblib>=1.5.2 (from mlxtend)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (24.2)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (11.1.0)
Requirement already satisfied: pyparsing>=3 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn>=1.8.0->mlxtend) (3.5.0)
Downloading mlxtend-0.24.0-py3-none-any.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 23.6 MB/s eta 0:00:00
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading matplotlib-3.10.8-cp313-cp313-macosx_11_0_arm64.whl (8.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 21.7 MB/s eta 0:00:00 MB/s eta 0:00:01
Downloading numpy-2.4.2-cp313-cp313-macosx_14_0_arm64.whl (5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 25.6 MB/s eta 0:00:00
Downloading pandas-3.0.0-cp313-cp313-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 27.9 MB/s eta 0:00:00 MB/s eta 0:00:01
Using cached scikit_learn-1.8.0-cp313-cp313-macosx_12_0_arm64.whl (8.0 MB)
Downloading scipy-1.17.0-cp313-cp313-macosx_14_0_arm64.whl (20.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.1/20.1 MB 25.2 MB/s eta 0:00:00 MB/s eta 0:00:01:01
Installing collected packages: numpy, joblib, scipy, pandas, scikit-learn, matplotlib, mlxtend
  Attempting uninstall: numpy
    Found existing installation: numpy 2.1.3
    Uninstalling numpy-2.1.3:
      Successfully uninstalled numpy-2.1.3
  Attempting uninstall: joblib━━━━━━━━━━━━━━━━━━━━━━━━ 0/7 [numpy]
    Found existing installation: joblib 1.4.2━━━━━ 0/7 [numpy]
    Uninstalling joblib-1.4.2:━━━━━━━━━━━━━━━━━━━━ 0/7 [numpy]
      Successfully uninstalled joblib-1.4.2━━━━━━━ 0/7 [numpy]
  Attempting uninstall: scipym╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/7 [joblib]
    Found existing installation: scipy 1.15.3━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/7 [joblib]
    Uninstalling scipy-1.15.3:━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/7 [scipy]lib]
      Successfully uninstalled scipy-1.15.3╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/7 [scipy]
  Attempting uninstall: pandas━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/7 [scipy]
    Found existing installation: pandas 2.2.3[0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/7 [scipy]
    Uninstalling pandas-2.2.3:━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━ 3/7 [pandas]
      Successfully uninstalled pandas-2.2.35;237m╺━━━━━━━━━━━━━━━━━━━━━━ 3/7 [pandas]
  Attempting uninstall: scikit-learn━━╺━━━━━━━━━━━━━━━━━━━━━━ 3/7 [pandas]
    Found existing installation: scikit-learn 1.6.1[0m━━━━━━━━━━━━━━━━━━━━━━ 3/7 [pandas]
    Uninstalling scikit-learn-1.6.1:━━━━━━━╸━━━━━━━━━━━━━━━━━ 4/7 [scikit-learn]
      Successfully uninstalled scikit-learn-1.6.1;249;38;114m╸━━━━━━━━━━━━━━━━━ 4/7 [scikit-learn]
  Attempting uninstall: matplotlib━━━━━━━━━╸━━━━━━━━━━━━━━━━━ 4/7 [scikit-learn]
    Found existing installation: matplotlib 3.10.0249;38;114m╸━━━━━━━━━━━━━━━━━ 4/7 [scikit-learn]
    Uninstalling matplotlib-3.10.0:━━━━━━━━━━━━━━╸━━━━━━━━━━━ 5/7 [matplotlib]
      Successfully uninstalled matplotlib-3.10.0━╸━━━━━━━━━━━ 5/7 [matplotlib]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [mlxtend]━━━ 6/7 [mlxtend]atplotlib]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.45.1 requires pandas<3,>=1.4.0, but you have pandas 3.0.0 which is incompatible.
numba 0.61.0 requires numpy<2.2,>=1.24, but you have numpy 2.4.2 which is incompatible.
sklearn-compat 0.1.3 requires scikit-learn<1.7,>=1.2, but you have scikit-learn 1.8.0 which is incompatible.
Successfully installed joblib-1.5.3 matplotlib-3.10.8 mlxtend-0.24.0 numpy-2.4.2 pandas-3.0.0 scikit-learn-1.8.0 scipy-1.17.0

In [3]:
import numpy as np
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

In [5]:

df = pd.read_csv('France_online_retail.csv')
df

,InvoiceNo,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
0,536370,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,536852,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,536974,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,537065,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,537463,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,580986,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
388,581001,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
389,581171,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
390,581279,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
391,581587,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
df = df.drop('InvoiceNo', axis =1);
df

,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
388,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
389,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
390,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
391,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [44]:
freq_items = apriori(df, min_support=0.12, use_colnames = True)
# the lesser the min_support, the more the values it displays 
#0.15

/opt/anaconda3/lib/python3.13/site-packages/mlxtend/frequent_patterns/fpcommon.py:175: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [ ]:
#one hot encoding help you to make

In [46]:
print(freq_items.shape)

(24, 2)

In [47]:
freq_items.sort_values(by=['support'], ascending=False)

     support                                           itemsets
6   0.765306                                          (POSTAGE)
7   0.188776                               (RABBIT NIGHT LIGHT)
9   0.181122                    (RED TOADSTOOL LED NIGHT LIGHT)
5   0.170918                 (PLASTERS IN TIN WOODLAND ANIMALS)
3   0.168367                    (PLASTERS IN TIN CIRCUS PARADE)
20  0.165816                      (POSTAGE, RABBIT NIGHT LIGHT)
21  0.158163           (POSTAGE, RED TOADSTOOL LED NIGHT LIGHT)
11  0.158163               (ROUND SNACK BOXES SET OF4 WOODLAND)
1   0.153061                          (LUNCH BAG RED RETROSPOT)
18  0.147959           (POSTAGE, PLASTERS IN TIN CIRCUS PARADE)
22  0.147959      (ROUND SNACK BOXES SET OF4 WOODLAND, POSTAGE)
2   0.142857                 (LUNCH BOX WITH CUTLERY RETROSPOT)
13  0.137755                      (SET/6 RED SPOTTY PAPER CUPS)
19  0.137755        (POSTAGE, PLASTERS IN TIN WOODLAND ANIMALS)
8   0.137755                         (RED RETROSPOT MINI CASES)
4   0.137755                         (PLASTERS IN TIN SPACEBOY)
12  0.132653               (SET/20 RED RETROSPOT PAPER NAPKINS)
14  0.127551                    (SET/6 RED SPOTTY PAPER PLATES)
0   0.125000                           (LUNCH BAG APPLE DESIGN)
15  0.125000                               (SPACEBOY LUNCH BOX)
10  0.125000                         (REGENCY CAKESTAND 3 TIER)
17  0.122449                 (LUNCH BAG RED RETROSPOT, POSTAGE)
16  0.122449                (STRAWBERRY LUNCH BOX WITH CUTLERY)
23  0.122449  (SET/6 RED SPOTTY PAPER PLATES, SET/6 RED SPOT...

In [48]:
#rules = association_rules(freq_items,metric ='confidence', min_thresholds=0.6);
rules = association_rules(freq_items, metric='confidence', min_threshold=0.6)

In [49]:
print(rules.shape)

(8, 14)

In [50]:
rules.sort_values(by=['confidence'], ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
6,(SET/6 RED SPOTTY PAPER PLATES),(SET/6 RED SPOTTY PAPER CUPS),0.127551,0.137755,0.122449,0.960000,6.968889,1.0,0.104878,21.556122,0.981725,0.857143,0.953609,0.924444
5,(ROUND SNACK BOXES SET OF4 WOODLAND),(POSTAGE),0.158163,0.765306,0.147959,0.935484,1.222366,1.0,0.026916,3.637755,0.216092,0.190789,0.725105,0.564409
7,(SET/6 RED SPOTTY PAPER CUPS),(SET/6 RED SPOTTY PAPER PLATES),0.137755,0.127551,0.122449,0.888889,6.968889,1.0,0.104878,7.852041,0.993343,0.857143,0.872645,0.924444
1,(PLASTERS IN TIN CIRCUS PARADE),(POSTAGE),0.168367,0.765306,0.147959,0.878788,1.148283,1.0,0.019107,1.936224,0.155278,0.188312,0.483531,0.536061
3,(RABBIT NIGHT LIGHT),(POSTAGE),0.188776,0.765306,0.165816,0.878378,1.147748,1.0,0.021345,1.929705,0.158684,0.210356,0.481786,0.547523
4,(RED TOADSTOOL LED NIGHT LIGHT),(POSTAGE),0.181122,0.765306,0.158163,0.873239,1.141033,1.0,0.019549,1.851474,0.150940,0.200647,0.459890,0.539953
2,(PLASTERS IN TIN WOODLAND ANIMALS),(POSTAGE),0.170918,0.765306,0.137755,0.805970,1.053134,1.0,0.006950,1.209576,0.060855,0.172524,0.173264,0.492985
0,(LUNCH BAG RED RETROSPOT),(POSTAGE),0.153061,0.765306,0.122449,0.800000,1.045333,1.0,0.005310,1.173469,0.051205,0.153846,0.147826,0.480000

In [ ]:
#Lift and Leverage - the propability of the consiquesnce and the 
#lift is ratio
#Leverage is the difference of the two
#you will be told to use confidence as you metric