# 7CS033 Assignment Task 5

### Complete the following tasks.

#### You should comment on your code where appropriate. Failing to add comments may result in a mark deduction.

#### You should write any explainations in the report cell if the task explicitly asks for this or if you wish to expand upon your solution.

#### Ensure you have ran your code cell and printed any of the required outputs. If necessary you can use more than one code cell.

## T5.1: Download the 'Portugal_online_retail', 'Sweden_online_retail, and 'UK_online_retail' datasets from Canvas. Apply the apriori algorithm to all datasets using three different confidence levels. Select one confidence level for each dataset that you think works better. Determine the first three most important rules for each dataset using the selected confidence level and report them in the report cell. Explain what each rule means (Completing the report cell is required) (10%).

NOTE: You should comment on your code

In [23]:
############# WRITE YOUR CODE IN THIS CELL (IF APPLICABLE)####################
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [24]:
#import portugal, sweden and uk dataset
df_portugal = pd.read_csv('Portugal_online_retail.csv', dtype={'InvoiceNo': str})
df_sweden = pd.read_csv('Sweden_online_retail.csv', dtype={'InvoiceNo': str})
df_uk = pd.read_csv('UK_online_retail.csv', dtype={'InvoiceNo': str})

In [25]:
#Drop the InvoiceNo column
df_portugal = df_portugal.drop('InvoiceNo', axis =1);
df_sweden = df_sweden.drop('InvoiceNo', axis =1);
df_uk = df_uk.drop('InvoiceNo', axis =1);

In [26]:
# Convert 0/1 to boolean (VERY IMPORTANT)
df_portugal = df_portugal.astype(bool)
df_sweden = df_sweden.astype(bool)
df_uk = df_uk.astype(bool)

In [27]:
print(f"{df_portugal.shape[0]} = Portugal rows!")
print(f"{df_sweden.shape[0]} = Sweden rows!")
print(f"{df_uk.shape[0]} = UK rows!")

58 = Portugal rows!
36 = Sweden rows!
18667 = UK rows!

In [6]:
#Since Portugal and Sweden are very small datasets, we must use lower support/confidence.
#For UK (large dataset), we can use higher thresholds.

### PORTUGAL - RUN APRIORI (Different support per dataset)

In [7]:
#For Small datase, support cannot be too high (you will lose patterns)
#For Large dataset, support must be lower to capture frequent combinations

##### GENERATE FREQUENCY WITH 3 DIFFERENT SUPPORT LEVELS

In [8]:
# Test three support values
frequent_p_01 = apriori(df_portugal, min_support=0.04, use_colnames=True);
frequent_p_05 = apriori(df_portugal, min_support=0.05, use_colnames=True);
frequent_p_10 = apriori(df_portugal, min_support=0.10, use_colnames=True);

In [9]:
print("Number of Frequent Itemsets for 0.04:", len(frequent_p_01))
print("Number of Frequent Itemsets for 0.05:", len(frequent_p_05))
print("Number of Frequent Itemsets for 0.10:", len(frequent_p_10))

Number of Frequent Itemsets for 0.04: 7446
Number of Frequent Itemsets for 0.05: 7446
Number of Frequent Itemsets for 0.10: 110

In [10]:
#For the Portugal dataset, a support of 0.10 is best because it produces a manageable number of 
#meaningful itemsets, while lower support values generate too many noisy itemsets

##### GENERATE RULES WITH 3 DIFFERENT CONFIDENCE LEVELS

In [11]:
# Generate association rules (try different confidence levels)
rules_03 = association_rules(frequent_p_10, metric="confidence", min_threshold=0.3)
rules_05 = association_rules(frequent_p_10, metric="confidence", min_threshold=0.5)
rules_07 = association_rules(frequent_p_10, metric="confidence", min_threshold=0.7)

print("Confidence 0.3:", len(rules_03))
print("Confidence 0.5:", len(rules_05))
print("Confidence 0.7:", len(rules_07))

Confidence 0.3: 317
Confidence 0.5: 300
Confidence 0.7: 209

In [12]:
#The best association rules for Portugal are those with a confidence threshold of 0.5 because they balance 
#reliability and quantity, capturing meaningful patterns without being too noisy or too restrictive.

In [13]:
# Select confidence = 0.5
rules_portugal = rules_05

# Sort by lift (higher lift = stronger rule)
top_portugal = rules_portugal.sort_values(by='lift', ascending=False).head(3)
top_portugal

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
58,frozenset({SCANDINAVIAN PAISLEY PICNIC BAG}),frozenset({PINK VINTAGE PAISLEY PICNIC BAG}),0.120690,0.137931,0.120690,1.00,7.25,1.0,0.104043,inf,0.980392,0.875,1.000000,0.9375
263,frozenset({JUMBO BAG SCANDINAVIAN BLUE PAISLEY...,"frozenset({LUNCH BAG PINK POLKADOT, JUMBO SHOP...",0.137931,0.103448,0.103448,0.75,7.25,1.0,0.089180,3.586207,1.000000,0.750,0.721154,0.8750
264,frozenset({JUMBO BAG SCANDINAVIAN BLUE PAISLEY...,"frozenset({JUMBO BAG PINK VINTAGE PAISLEY, LUN...",0.137931,0.103448,0.103448,0.75,7.25,1.0,0.089180,3.586207,1.000000,0.750,0.721154,0.8750

### SWEDEN - RUN APRIORI (Different support per dataset)

##### GENERATE FREQUENCY WITH 3 DIFFERENT SUPPORT LEVELS

In [14]:
# Test three support values

frequent_s_08 = apriori(df_sweden, min_support=0.08, use_colnames=True)
frequent_s_10 = apriori(df_sweden, min_support=0.10, use_colnames=True)
frequent_s_15 = apriori(df_sweden, min_support=0.15, use_colnames=True)

print("Support 0.08:", len(frequent_s_08))
print("Support 0.10:", len(frequent_s_10))
print("Support 0.15:", len(frequent_s_15))

Support 0.08: 118
Support 0.10: 25
Support 0.15: 3

In [15]:
#0.10 provided a balanced and meaningful number of itemsets (25) while 0.08 produced too many 
#frequent itemsets (118), indicating noise, while 0.15 produced too few (3)

##### GENERATE RULES WITH 3 DIFFERENT CONFIDENCE LEVELS

In [16]:
# Generate association rules (try different confidence levels)
rules_s_04 = association_rules(frequent_s_10, metric="confidence", min_threshold=0.4)
rules_s_05 = association_rules(frequent_s_10,  metric="confidence", min_threshold=0.5)
rules_s_07 = association_rules(frequent_s_10, metric="confidence", min_threshold=0.7)


print("Confidence 0.4:", len(rules_s_04))
print("Confidence 0.5:", len(rules_s_05))
print("Confidence 0.7:", len(rules_s_07))

Confidence 0.4: 6
Confidence 0.5: 6
Confidence 0.7: 6

In [17]:
#0.7 Confidence was selected because all six rules remained the same across 0.4, 0.5, and 0.7, meaning the 
#rules are already strong, so using the higher threshold ensures greater reliability without losing any rules

In [18]:
# Select confidence = 0.5
rules_sweden = rules_s_05

# Sort by lift (higher lift = stronger rule)
top_sweden= rules_sweden.sort_values(by='lift', ascending=False).head(3)
top_sweden

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1,frozenset({PACK OF 72 RETROSPOT CAKE CASES}),frozenset({PACK OF 60 SPACEBOY CAKE CASES}),0.111111,0.111111,0.111111,1.0,9.000000,1.0,0.098765,inf,1.000000,1.000000,1.0,1.000000
2,frozenset({PACK OF 60 SPACEBOY CAKE CASES}),frozenset({PACK OF 72 RETROSPOT CAKE CASES}),0.111111,0.111111,0.111111,1.0,9.000000,1.0,0.098765,inf,1.000000,1.000000,1.0,1.000000
0,frozenset({GUMBALL COAT RACK}),frozenset({POSTAGE}),0.138889,0.611111,0.138889,1.0,1.636364,1.0,0.054012,inf,0.451613,0.227273,1.0,0.613636

### UK - RUN APRIORI (Different support per dataset)

##### GENERATE FREQUENCY WITH 3 DIFFERENT SUPPORT LEVELS

In [22]:
### UK - TEST SUPPORT VALUES
frequent_uk_009 = apriori(df_uk, min_support=0.009, use_colnames=True)
frequent_uk_01 = apriori(df_uk, min_support=0.01, use_colnames=True)
frequent_uk_02 = apriori(df_uk, min_support=0.02, use_colnames=True)

print("Support 0.009:", len(frequent_uk_009))
print("Support 0.01:", len(frequent_uk_01))
print("Support 0.02:", len(frequent_uk_02))

Support 0.009: 2606
Support 0.01: 1970
Support 0.02: 369

In [ ]:
#Support = 0.01 is the best choice because it captures meaningful and recurring purchasing patterns without being 
#too restrictive or generating excessive noise. Lower support includes too many insignificant combinations, 
#while higher support removes useful associations

##### GENERATE RULES WITH 3 DIFFERENT CONFIDENCE LEVELS

In [28]:
rules_uk_04 = association_rules(frequent_uk_01, metric="confidence", min_threshold=0.4)
rules_uk_05 = association_rules(frequent_uk_01, metric="confidence", min_threshold=0.5)
rules_uk_06 = association_rules(frequent_uk_01, metric="confidence", min_threshold=0.6)

print("Confidence 0.4:", len(rules_uk_04))
print("Confidence 0.5:", len(rules_uk_05))
print("Confidence 0.6:", len(rules_uk_06))

Confidence 0.4: 1502
Confidence 0.5: 1055
Confidence 0.6: 667

In [29]:
# Select confidence = 0.5
rules_uk = rules_uk_05

# Sort by lift (higher lift = stronger rule)
top_uk= rules_uk.sort_values(by='lift', ascending=False).head(3)
top_uk

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
501,"frozenset({HERB MARKER PARSLEY, HERB MARKER RO...",frozenset({HERB MARKER THYME}),0.011089,0.012321,0.010553,0.951691,77.240055,1.0,0.010417,20.444951,0.998122,0.820833,0.951088,0.904106
506,frozenset({HERB MARKER THYME}),"frozenset({HERB MARKER PARSLEY, HERB MARKER RO...",0.012321,0.011089,0.010553,0.856522,77.240055,1.0,0.010417,6.892409,0.999367,0.820833,0.854913,0.904106
496,"frozenset({HERB MARKER MINT, HERB MARKER THYME})",frozenset({HERB MARKER ROSEMARY}),0.010714,0.012375,0.010232,0.955000,77.173095,1.0,0.010099,21.947227,0.997732,0.795833,0.954436,0.890920

######################## Write your report in this cell (if applicable) #############################

PORTUGAL DATASET
For the Portugal dataset, a support of 0.10 is best because it produces a manageable number of 
meaningful itemsets, while lower support values generate too many noisy itemsets

The best association rules for Portugal are those with a confidence threshold of 0.5 because they balance 
reliability and quantity, capturing meaningful patterns without being too noisy or too restrictive.

SWEDEN DATASET
0.10 was chosen as it provided a balanced and meaningful number of itemsets (25) while 0.08 produced too many 
#frequent itemsets (118), indicating noise, while 0.15 produced too few (3)

0.5 is a better confidence threshold because 50% confidence means the rule is correct at 
least half the time, which gives good reliability without removing too many rules


UK DATASET 
Support = 0.01 is the best choice because it captures meaningful and recurring purchasing patterns without being too restrictive 
or generating excessive noise. Lower support includes too many insignificant combinations, while higher support removes useful associations

Confidence = 0.5 is appropriate because it ensures the rules are reliable and strong enough to be meaningful, 
while still retaining a sufficient number of patterns for analysis