In [2]:
import pandas as pd
import numpy as np

In [6]:
text = ["This is the NLP lecture by Jordan **",
        "IN this lectures I'll be explaining various DATA-CLEANING Techniques",
        "I hope you are PAYing attention! &&&",
        "Creating example text is pretty boring",
        "wlv ftw",
        "Running bulls cause chaotic situations"]

df = pd.DataFrame({'text': text})
df

                                                text
0               This is the NLP lecture by Jordan **
1  IN this lectures I'll be explaining various DA...
2               I hope you are PAYing attention! &&&
3             Creating example text is pretty boring
4                                            wlv ftw
5             Running bulls cause chaotic situations

In [5]:
df = pd.DataFrame({'text':text})
df

NameError: name 'text' is not defined

In [10]:
df['lower'] = df['text'].apply(lambda x: " ".join(x.lower() for x in x.split()))

In [9]:
df

,text,lower
0,This is the NLP lecture by Jordan **,thisisthenlplecturebyjordan**
1,IN this lectures I'll be explaining various DA...,inthislecturesi'llbeexplainingvariousdata-clea...
2,I hope you are PAYing attention! &&&,ihopeyouarepayingattention!&&&
3,Creating example text is pretty boring,creatingexampletextisprettyboring
4,wlv ftw,wlvftw
5,Running bulls cause chaotic situations,runningbullscausechaoticsituations

In [ ]:
import string
string.punctuation

In [ ]:
'!"#$%^%^&*(+_)(*&^%#@!

In [ ]:
df['punc1'] = df['lower'].apply(lambda x: " ".join(i for i in x if i not in string.punctuation))

In [11]:
df

,text,lower
0,This is the NLP lecture by Jordan **,this is the nlp lecture by jordan **
1,IN this lectures I'll be explaining various DA...,in this lectures i'll be explaining various da...
2,I hope you are PAYing attention! &&&,i hope you are paying attention! &&&
3,Creating example text is pretty boring,creating example text is pretty boring
4,wlv ftw,wlv ftw
5,Running bulls cause chaotic situations,running bulls cause chaotic situations

In [12]:
import re

In [13]:
df['punc2'] = df['lower'].apply(lambda x: "".join(re.findall(r'[a-zA-Z+" "]',x))) #remove other characters

In [14]:
df

,text,lower,punc2
0,This is the NLP lecture by Jordan **,this is the nlp lecture by jordan **,this is the nlp lecture by jordan
1,IN this lectures I'll be explaining various DA...,in this lectures i'll be explaining various da...,in this lectures ill be explaining various dat...
2,I hope you are PAYing attention! &&&,i hope you are paying attention! &&&,i hope you are paying attention
3,Creating example text is pretty boring,creating example text is pretty boring,creating example text is pretty boring
4,wlv ftw,wlv ftw,wlv ftw
5,Running bulls cause chaotic situations,running bulls cause chaotic situations,running bulls cause chaotic situations

In [15]:
import nltk

In [16]:
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /Users/oeze/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [23]:
allStopwords = stopwords.words('english')
print(allStopwords)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [24]:
df['stopword'] = df['punc2'].apply(lambda x:" ".join(i for i in x.split() if i not in allStopwords))

In [25]:
df

,text,lower,punc2,stopword
0,This is the NLP lecture by Jordan **,this is the nlp lecture by jordan **,this is the nlp lecture by jordan,nlp lecture jordan
1,IN this lectures I'll be explaining various DA...,in this lectures i'll be explaining various da...,in this lectures ill be explaining various dat...,lectures ill explaining various datacleaning t...
2,I hope you are PAYing attention! &&&,i hope you are paying attention! &&&,i hope you are paying attention,hope paying attention
3,Creating example text is pretty boring,creating example text is pretty boring,creating example text is pretty boring,creating example text pretty boring
4,wlv ftw,wlv ftw,wlv ftw,wlv ftw
5,Running bulls cause chaotic situations,running bulls cause chaotic situations,running bulls cause chaotic situations,running bulls cause chaotic situations

In [ ]:
df['lower_punc_stop'] = df['stopword'].apply() #missed this

In [27]:
from textblob import TextBlob

ModuleNotFoundError: No module named 'Textblob'